name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.8
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push user-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./user-service
          file: ./user-service/Dockerfile
          push: false

      - name: Build and push auction-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./auction-service
          file: ./auction-service/Dockerfile
          push: false

      - name: Build and push order-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./order-service
          file: ./order-service/Dockerfile
          push: false
    
      - name: Build and push product-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./product-service
          file: ./product-service/Dockerfile
          push: false

      - name: Build and push admin-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./admin-service
          file: ./admin-service/Dockerfile
          push: false

      - name: Compose up
        run: docker-compose up -d
